apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: devops-portal
labels:
  - pairs:
      app.kubernetes.io/name: devops-portal-frontend
      app.kubernetes.io/part-of: devops-portal
    includeSelectors: true
resources:
  - namespace.yaml
  - frontend.yaml   # Deployment + HPA + Service
  - ingress.yaml
